---
services:
    php:
        build: ./php/${PHP_VERSION}
        container_name: bitrix_php
        volumes:
            - ${SITE_PATH}:/var/www/bitrix
            - ./logs/php:/var/log/php
            - /etc/localtime:/etc/localtime/:ro
        environment:
            TZ: Europe/Moscow
        networks:
            - bitrixdock
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: bitrix_${WEB_SERVER_TYPE}
        depends_on:
            - php
        volumes:
            - ${SITE_PATH}:/var/www/bitrix
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - /etc/localtime:/etc/localtime/:ro
        ports:
            - '81:80'
        networks:
            - bitrixdock
        environment:
            TZ: Europe/Moscow
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'

networks:
    bitrixdock:
        driver: bridge
